POST  http://localhost:3001/app/events/post
Content-Type: application/json

{
    "content": "This is another events post",
    "title": "Study Session",
    "contact": "12344",
    "user_id": "625308bba19310bf2a848824"
}